### ISSUE TITLE
Optional parameters in EncryptedField constructor

### ISSUE THREAD

**Issue by gabrovex** [paragonie/ciphersweet#33]
Hi.
In the [instantiation](https://github.com/paragonie/ciphersweet/blob/master/src/EncryptedField.php#L50) of an encrypted field we pass as parameter the table and field name.
Following your example `$ssn = (new EncryptedField($engine, 'contacts', 'ssn'));`
Those are actually optional parameters. For my needs avoiding using those would simplify a lot (together with naming the blind index with a generic default name).
I'm wondering if those optional fields are actually something that gives an additional salt to our cipher text or if they are not relevant for the security.

**Comment by paragonie-scott** [comment]
> I'm wondering if those optional fields are actually something that gives an additional salt to our cipher text or if they are not relevant for the security.

The table name and column name are used to generate two distinct subkeys for each column: One for encryption/decryption, the other is the root key for the blind indexes on that column. Each blind index root key can be used with the name of the column to generate many subkeys, so that each blind index has a distinct key.

This is explained here: https://github.com/paragonie/ciphersweet/blob/master/docs/internals/01-key-hierarchy.md

The purpose of this is to simplify key management for typical (i.e. relational) database schemas.

> For my needs avoiding using those would simplify a lot (together with naming the blind index with a generic default name).

It'd be possible to design a secure scheme that flattened `table + column` to just `column` for the first step. However, there are a few questions that this raises:

1. What should this design be called? `FlatStructure\EncryptedField`?
2. Should this be included in CipherSweet or built into a separate project?
3. How can we still empower the typical use-case (`table + column => {encKey, indexKey1, indexKey2, ...}`) without confusing end users, if it's implemented in CipherSweet?

The main change would need to lie here:

https://github.com/paragonie/ciphersweet/blob/945591ecc413bbcae044a7d9e640a5351c3c5b63/src/EncryptedField.php#L55-L58

Instead, an alternative API (`getFlatSymmetricKey`?) would need to be used by the new classes, which only accepted a generic argument.

A simpler approach may be to do something like this:

```php
<?php
use ParagonIE\CipherSweet\EncryptedField;

define('SOME_DUMMY_CONSTANT', 'Something related to your project in particular');

function get_encrypted_field(CipherSweet $engine, $columnName = ''): EncryptedField
{
    return new EncryptedField($engine, SOME_DUMMY_CONSTANT, $columnName);
}
```

**Comment by gabrovex** [comment]
Ok, everything much clearer now. Thanks!
