### ISSUE TITLE
Understanding blind indexing security

### ISSUE THREAD

**Issue by storojs72** [paragonie/ciphersweet#39]
As I understand, if I want to improve performance of selecting a given encrypted field, I should create database index on another field that contains blind indexes for encrypted records (stored in encrypted field). Thus, I will be able to select encrypted records faster with a help of those database index.

Can you please explain cases when I will need to create more than one blind index for a given encrypted field. 

Thanks.

**Comment by paragonie-scott** [comment]
It's rather hard to provide an example for this that won't confuse some people. My "go to" example is medical records, but I'm open to suggestions for more relatable scenarios.

---

Scenario: You're building software for a health care provider.

Imagine you need to store a person's HIV status (reactive = TRUE, nonreactive = FALSE, untested = NULL) for a medical database, and you want to encrypt this value.

Imagine that, also, at some point in the future, you will also need to query it (e.g. "find all untested patients in a specificregion to schedule an STI screening panel").

Furthermore, imagine that you also use social security numbers for insurance paperwork and to deduplicate patients with the same first and last name (not super common, but does happen). You'll also want to be encrypting this value.

If you can easily imagine these operational requirements in the same organization, you can imagine the following blind indexes being created:

* First Initial + Last Name
* Last Four Digits of SSN
* First Name + Last Four Digits of SSN
* HIV Status + ZIP Code
* HIV Status + Last Four Digits of SSN

You almost never want a boolean value (i.e. HIV status) to be directly indexed, because of its short domain size. You'll want to combine it with other fields **depending on the kind of `SELECT` queries you're making**.

**Comment by storojs72** [comment]
Thank you. Pretty simple.

I also try to understand the security formula from Blind Index Information Leaks section of documentation. For example, if I have field with R=20000 encrypted days of week (Mon, Tue, Wed ...) which has low entropy (e.g. short domain size: 7 distinct values, so K = 3 bits approximately),` one blind index for this field. With a help of formula I have obtained that probability of coincidence is 1 / 2^(-3) = 0,125 for any blind index with length greater than L > 3. Number of coincidences C = 2500. 

I understand that 0,125 - is an attacker's probability of guessing plaintext value of encrypted day of week. But what does C = 2500 mean?

**Comment by paragonie-scott** [comment]
C = 2500 means that a query based solely on that blind index will return 2500 rows on average.

**Comment by paragonie-scott** [comment]
https://ciphersweet.paragonie.com/faq#multiple-indexes I've added an FAQ page to the documentation to explain this (and similar topics).
