### ISSUE TITLE
Would it be possible to tag this commit?

### ISSUE THREAD

**Issue by wdavis** [paragonie/ciphersweet#61]
Would it be possible to tag f73aaea31f743dad8145f344d93503c4d9f950a8 as a release?

This fixes the "Private methods cannot be final..." issue in PHP 8. I'm hitting this often in 2.0.2.

Would definitely appreciate it! Thank you

**Comment by paragonie-security** [comment]
Not yet. There are breaking changes and this is going to land in v3.0.0.

**Comment by wdavis** [comment]
Ah, ok. I'll work around it for now.

Look forward to 3.0!

**Comment by paragonie-security** [comment]
Looking at the commit history, we can tag a different commit (the one _right after_ 2.0.2).

**Comment by wdavis** [comment]
I completely overlooked that one (1ca3cfe2d05abea29f1e48613db9f0b6ca4e723e). That should work!

**Comment by paragonie-security** [comment]
Version 3.0.0 is out now. The BC breaks are mostly *default behavior* (if you explicitly select `ModernCrypto` instead of letting the library decide, your BC story is nonbreaking).

Version 3.0.0 is more powerful than 2.x, and lets you extend CipherSweet safely in ways that a lot of people want to: https://github.com/paragonie/ciphersweet/issues/59#issuecomment-864675404
